name: Train ML Model
on:
  push:
    paths:
      - 'MLProject/**'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Setting up job"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: conda info --envs

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Install dependencies
        run: conda env update --file MLProject/conda.yaml --name mlflow-env --prune

      - name: Install MLflow in Conda
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mlflow-env
          pip install mlflow==2.19.0  # Sinkronkan versi dengan mlflow-skinny

      - name: Start MLflow Server and Set Tracking URI
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mlflow-env
          mlflow server --backend-store-uri ./mlruns --default-artifact-root ./mlruns --host 0.0.0.0 --port 5001 &
          sleep 5  # Tunggu server siap
          export MLFLOW_TRACKING_URI=http://localhost:5001
          echo "MLFLOW_TRACKING_URI is set to $MLFLOW_TRACKING_URI"

      - name: Run mlflow project
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mlflow-env
          cd MLProject
          mlflow run . --entry-point main --env-manager=local

      - name: Install Python dependencies
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate mlflow-env
          pip install -r MLProject/requirements.txt

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
          if-no-files-found: error