name: CI Pipeline for ML Model Training

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Set up job/checkout@v3
    - name: Set up job
      run: echo "Setting up job"

    # 2. Run actions/checkout@v3
    - name: Checkout code
      uses: actions/checkout@v3

    # 3. Set up Python 3.12.7
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # 4. Check Env
    - name: Check Environment
      run: |
        python --version
        pip --version

    # 5. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow

    # 6. Set MLflow Tracking URI
    - name: Set MLflow Tracking URI
      run: |
        mlflow server --host 0.0.0.0 --port 5000 &
        echo "MLFLOW_TRACKING_URI=http://localhost:5000" >> $GITHUB_ENV

    # 7. Run mlflow project
    - name: Run mlflow project
      run: |
        sleep 5 # Tunggu server MLflow start
        python modelling.py

    # 8. Install Python dependencies (opsional, sudah di atas)
    - name: Install additional Python dependencies
      run: pip install -r requirements.txt # Ulangi untuk memastikan

    # 9. Upload to Google Drive
    - name: Upload to Google Drive
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}

    # 10. Post Set up Python 3.12.7
    - name: Post Set up Python
      if: always()
      run: echo "Post Python setup"

    # 11. Post Run actions/checkout@v3
    - name: Post Checkout
      if: always()
      run: echo "Post checkout"

    # 12. Complete job
    - name: Complete job
      if: always()
      run: echo "Job completed"