name: Train ML Model
on:
  push:
    paths:
      - 'MLProject/**'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false
      - name: Install dependencies
        run: conda env update --file MLProject/conda.yaml --name mlflow-env --prune
      - name: Install MLflow
        run: pip install mlflow
      - name: Run mlflow project
        working-directory: MLProject
        env:
          MLFLOW_CONDA_RUN_COMMAND: "conda run"
        run: |
          mlflow run . --entry-point main --env-manager=local
          # Opsional: Pastikan model di-log (jika perlu tambahan)
          # mlflow models build-docker -m mlruns/0/<run-id>/artifacts/model -n mymodel
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/
          if-no-files-found: error