name: Retrain Model CI

on:
  push:
    branches: [ "main" ]

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup environment Conda
      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          auto-update-conda: true

      # Langkah 3: Install MLflow ke dalam environment base Conda
      - name: Install MLflow
        run: pip install mlflow

      # Langkah 4: Jalankan MLflow Project
      - name: Run MLflow Project
        working-directory: ./MLProject
        run: mlflow run .

      # Langkah 5: Upload Artefak
      - name: Upload mlruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-output
          path: mlruns/