name: Train ML Model
on:
  push:
    paths:
      - 'MLProject/**'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false
      - name: Install MLflow
        run: pip install mlflow
      - name: Run MLflow Project
        working-directory: MLProject
        env:
          MLFLOW_CONDA_RUN_COMMAND: "conda run"
        run: mlflow run . --entry-point main --env-manager=local
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/